Feat: use core vendor binaries

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -96,50 +96,113 @@ jobs:
         run: |
           npm install --no-save
       - name: "PHP Parallel Lint"
-        if: ${{ !cancelled() && hashFiles(format('{0}/vendor/bin/parallel-lint', inputs.plugin-key)) != '' }}
         run: |
           echo -e "\033[0;33mExecuting PHP Parallel Lint...\033[0m"
-          vendor/bin/parallel-lint --colors --exclude ./lib/ --exclude ./node_modules/ --exclude ./vendor/ --no-progress .
+          if [[ -f "vendor/bin/parallel-lint" ]]; then
+            vendor/bin/parallel-lint --colors --exclude ./lib/ --exclude ./node_modules/ --exclude ./vendor/ --no-progress .
+          elif [[ -f "../../vendor/bin/parallel-lint" ]]; then
+            ../../vendor/bin/parallel-lint --colors --exclude ./lib/ --exclude ./node_modules/ --exclude ./vendor/ --no-progress .
+          else
+            echo -e "\033[0;31mPHP Parallel Lint binary not found!\033[0m"
+            exit 1
+          fi
       - name: "PHP CodeSniffer"
-        if: ${{ !cancelled() && hashFiles(format('{0}/vendor/bin/phpcs', inputs.plugin-key)) != '' && hashFiles(format('{0}/.phpcs.xml', inputs.plugin-key)) != '' }}
+        if: ${{ !cancelled() && hashFiles(format('{0}/.phpcs.xml', inputs.plugin-key)) != '' }}
         run: |
           echo -e "\033[0;33mExecuting PHP CodeSniffer...\033[0m"
+          if [[ -f "vendor/bin/phpcs" ]]; then
+            vendor/bin/phpcs
+          elif [[ -f "../../vendor/bin/phpcs" ]]; then
+            ../../vendor/bin/phpcs
+          else
+            echo -e "\033[0;31mPHP CodeSniffer binary not found!\033[0m"
+            exit 1
+          fi
           vendor/bin/phpcs
       - name: "PHP-CS-Fixer"
-        if: ${{ !cancelled() && hashFiles(format('{0}/vendor/bin/php-cs-fixer', inputs.plugin-key)) != '' && hashFiles(format('{0}/.php-cs-fixer.php', inputs.plugin-key)) != '' }}
+        if: ${{ !cancelled() && hashFiles(format('{0}/.php-cs-fixer.php', inputs.plugin-key)) != '' }}
         run: |
           echo -e "\033[0;33mExecuting PHP-CS-Fixer...\033[0m"
-          PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer check --config=.php-cs-fixer.php --no-interaction --show-progress none
+          if [[ -f "vendor/bin/php-cs-fixer" ]]; then
+            PHP_CS_FIXER_IGNORE_ENV=1 vendor/bin/php-cs-fixer check --config=.php-cs-fixer.php --no-interaction --show-progress none
+          elif [[ -f "../../vendor/bin/php-cs-fixer" ]]; then
+            PHP_CS_FIXER_IGNORE_ENV=1 php ../../vendor/bin/php-cs-fixer check --config=.php-cs-fixer.php --no-interaction --show-progress none
+          else
+            echo -e "\033[0;31mPHP-CS-Fixer binary not found!\033[0m"
+            exit 1
+          fi
       - name: "PHPStan"
-        if: ${{ !cancelled() && hashFiles(format('{0}/vendor/bin/phpstan', inputs.plugin-key)) != '' && hashFiles(format('{0}/phpstan.neon', inputs.plugin-key)) != '' }}
+        if: ${{ !cancelled() && hashFiles(format('{0}/phpstan.neon', inputs.plugin-key)) != '' }}
         run: |
           echo -e "\033[0;33mExecuting PHPStan...\033[0m"
-          vendor/bin/phpstan analyze --ansi --memory-limit=2G --no-interaction --no-progress
+          if [[ -f "vendor/bin/phpstan" ]]; then
+            vendor/bin/phpstan analyze --ansi --memory-limit=2G --no-interaction --no-progress
+          elif [[ -f "../../vendor/bin/phpstan" ]]; then
+            ../../vendor/bin/phpstan analyze --ansi --memory-limit=2G --no-interaction --no-progress
+          else
+            echo -e "\033[0;31mPHPStan binary not found!\033[0m"
+            exit 1
+          fi
       - name: "Psalm"
         if: ${{ !cancelled() && hashFiles(format('{0}/psalm.xml', inputs.plugin-key)) != '' }}
         run: |
           echo -e "\033[0;33mExecuting Psalm...\033[0m"
-          php ../../vendor/bin/psalm --long-progress --output-format=github
+          if [[ -f "vendor/bin/psalm" ]]; then
+            vendor/bin/psalm --long-progress --output-format=github
+          elif [[ -f "../../vendor/bin/psalm" ]]; then
+            ../../vendor/bin/psalm --long-progress --output-format=github
+          else
+            echo -e "\033[0;31mPsalm binary not found!\033[0m"
+            exit 1
+          fi
       - name: "Rector"
-        if: ${{ !cancelled() && hashFiles(format('{0}/vendor/bin/rector', inputs.plugin-key)) != '' && hashFiles(format('{0}/rector.php', inputs.plugin-key)) != '' }}
+        if: ${{ !cancelled() && hashFiles(format('{0}/rector.php', inputs.plugin-key)) != '' }}
         run: |
           echo -e "\033[0;33mExecuting Rector...\033[0m"
-          php vendor/bin/rector process --dry-run --ansi
+          if [[ -f "vendor/bin/rector" ]]; then
+            vendor/bin/rector process --dry-run --ansi
+          elif [[ -f "../../vendor/bin/rector" ]]; then
+            ../../vendor/bin/rector process --dry-run --ansi
+          else
+            echo -e "\033[0;31mRector binary not found!\033[0m"
+            exit 1
+          fi
       - name: "JS Lint"
-        if: ${{ !cancelled() && hashFiles(format('{0}/node_modules/.bin/eslint', inputs.plugin-key)) != '' && (hashFiles(format('{0}/eslint.config.js', inputs.plugin-key)) != '' || hashFiles(format('{0}/eslint.config.mjs', inputs.plugin-key)) != '' || hashFiles(format('{0}/eslint.config.cjs', inputs.plugin-key)) != '' || hashFiles(format('{0}/.eslintrc.js', inputs.plugin-key)) != '') }}
+        if: ${{ !cancelled() && (hashFiles(format('{0}/eslint.config.js', inputs.plugin-key)) != '' || hashFiles(format('{0}/eslint.config.mjs', inputs.plugin-key)) != '' || hashFiles(format('{0}/eslint.config.cjs', inputs.plugin-key)) != '' || hashFiles(format('{0}/.eslintrc.js', inputs.plugin-key)) != '') }}
         run: |
           echo -e "\033[0;33mExecuting ESLint...\033[0m"
-          node_modules/.bin/eslint --color .
+          if [[ -f "node_modules/.bin/eslint" ]]; then
+            node_modules/.bin/eslint --color .
+          elif [[ -f "../../node_modules/.bin/eslint" ]]; then
+            ../../node_modules/.bin/eslint --color .
+          else
+            echo -e "\033[0;31mESLint binary not found!\033[0m"
+            exit 1
+          fi
       - name: "CSS Lint"
         if: ${{ !cancelled() && hashFiles(format('{0}/node_modules/.bin/stylelint', inputs.plugin-key)) != '' && hashFiles(format('{0}/.stylelintrc.js', inputs.plugin-key)) != '' }}
         run: |
           echo -e "\033[0;33mExecuting Stylelint...\033[0m"
-          node_modules/.bin/stylelint --color "**/*.css" "**/*.scss"
+          if [[ -f "node_modules/.bin/stylelint" ]]; then
+            node_modules/.bin/stylelint --color "**/*.css" "**/*.scss"
+          elif [[ -f "../../node_modules/.bin/stylelint" ]]; then
+            ../../node_modules/.bin/stylelint --color "**/*.css" "**/*.scss"
+          else
+            echo -e "\033[0;31mStylelint binary not found!\033[0m"
+            exit 1
+          fi
       - name: "Misc lint"
-        if: ${{ !cancelled() && hashFiles(format('{0}/vendor/bin/licence-headers-check', inputs.plugin-key)) != '' && hashFiles(format('{0}/tools/HEADER', inputs.plugin-key)) != '' }}
+        if: ${{ !cancelled() && hashFiles(format('{0}/tools/HEADER', inputs.plugin-key)) != '' }}
         run: |
           echo -e "\033[0;33mExecuting licence headers checks...\033[0m"
-          vendor/bin/licence-headers-check --ansi --no-interaction
+          if [[ -f "vendor/bin/licence-headers-check" ]]; then
+            vendor/bin/licence-headers-check --ansi --no-interaction
+          elif [[ -f "../../vendor/bin/licence-headers-check" ]]; then
+            ../../vendor/bin/licence-headers-check --ansi --no-interaction --header-file=tools/HEADER -d .
+          else
+            echo -e "\033[0;31mLicence headers check binary not found!\033[0m"
+            exit 1
+          fi
       - name: "Install plugin"
         if: ${{ !cancelled() }}
         working-directory: "/var/www/glpi"
@@ -159,14 +222,36 @@ jobs:
         if: ${{ !cancelled() && hashFiles(format('{0}/phpunit.xml', inputs.plugin-key)) != '' }}
         run: |
           echo -e "\033[0;33mExecuting PHPUnit...\033[0m"
-          php ../../vendor/bin/phpunit --colors=always
+          if [[ -f "vendor/bin/phpunit" ]]; then
+            vendor/bin/phpunit --colors=always
+          elif [[ -f "../../vendor/bin/phpunit" ]]; then
+            ../../vendor/bin/phpunit --colors=always
+          else
+            echo -e "\033[0;31mPHPUnit binary not found!\033[0m"
+            exit 1
+          fi
       - name: "Jest"
-        if: ${{ !cancelled() && hashFiles(format('{0}/node_modules/.bin/jest', inputs.plugin-key)) != '' && hashFiles(format('{0}/jest.config.js', inputs.plugin-key)) != '' }}
+        if: ${{ !cancelled() && hashFiles(format('{0}/jest.config.js', inputs.plugin-key)) != '' }}
         run: |
           echo -e "\033[0;33mExecuting Jest...\033[0m"
-          NODE_OPTIONS="--experimental-vm-modules" node_modules/.bin/jest --colors --forceExit
+          if [[ -f "node_modules/.bin/jest" ]]; then
+            NODE_OPTIONS="--experimental-vm-modules" node_modules/.bin/jest --colors --forceExit
+          elif [[ -f "../../node_modules/.bin/jest" ]]; then
+            NODE_OPTIONS="--experimental-vm-modules" ../../node_modules/.bin/jest --colors --forceExit
+          else
+            echo -e "\033[0;31mJest binary not found!\033[0m"
+            exit 1
+          fi
       - name: "TwigCS"
-        if: ${{ !cancelled() && hashFiles(format('{0}/vendor/bin/twigcs', inputs.plugin-key)) != '' && hashFiles(format('{0}/.twig_cs.dist.php', inputs.plugin-key)) != '' }}
+        if: ${{ !cancelled() && hashFiles(format('{0}/.twig_cs.dist.php', inputs.plugin-key)) != '' }}
         run: |
           echo -e "\033[0;33mExecuting TwigCS...\033[0m"
+          if [[ -f "vendor/bin/twigcs" ]]; then
+            vendor/bin/twigcs
+          elif [[ -f "../../vendor/bin/twigcs" ]]; then
+            ../../vendor/bin/twigcs
+          else
+            echo -e "\033[0;31mTwigCS binary not found!\033[0m"
+            exit 1
+          fi
           vendor/bin/twigcs
